name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno-version: [1.4.2]
        node-version: [14.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Set system environment variables
        run: |
          echo "./node_modules/.bin" >> $GITHUB_PATH
      - name: Build and test rimu
        run: |
          npm install
          deno cache -r src/deno/rimuc.ts
          deno run -A Drakefile.ts build
          deno run -A Drakefile.ts test